theme: jekyll-theme-slate
title: Harmonized Processes for Section 508 Testing: Baseline Tests for Software & Web Accessibility
description: This document contains accessibility design requirements and validation tests for software and Web accessibility. These tests are for measuring compliance with Section 508 of the Rehabilitation Act of 1973, as amended (29 U.S.C. 794d) .
